version: '3.8'

services:
  # MinIO Service
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_ADDRESS=:9000
      - MINIO_CONSOLE_ADDRESS=:9001
    command: server /data
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    restart: always

  # Next.js Application Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs_app
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - AUTH_SECRET=${AUTH_SECRET}
      - AUTH_URL=${AUTH_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - NODEMAILER_GOOGLE_SMTP_USER=${NODEMAILER_GOOGLE_SMTP_USER}
      - NODEMAILER_GOOGLE_ACCESS_TOKEN=${NODEMAILER_GOOGLE_ACCESS_TOKEN}
      - NODEMAILER_GOOGLE_REFRESH_TOKEN=${NODEMAILER_GOOGLE_REFRESH_TOKEN}
      - NEXT_PUBLIC_MINIO_URL=http://minio:9000
      - NEXT_PUBLIC_MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - NEXT_PUBLIC_MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    depends_on:
      - minio
    restart: always

  # Nginx Service
  nginx:
    container_name: nginx_server
    restart: unless-stopped
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf   # Mount Nginx configuration
      - ./certbot/conf:/etc/letsencrypt            # SSL certificates folder
      - ./certbot/www:/var/www/certbot             # Certbot challenge webroot
    depends_on:
      - app

  # Certbot for SSL Certificates
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email sadmansakib452@gmail.com -d sadman-workbench.zapto.org --agree-tos --non-interactive
    depends_on:
      - nginx

volumes:
  minio-data:
    driver: local
